name: Deploy to Server

on:
  workflow_run:
    workflows: ["Build & Push Docker Image"]
    types:
      - completed

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            # Go to project folder (clone if first time)
            if [ ! -d "/var/www/task-management" ]; then
              git clone https://github.com/Nozimjon04/task-management.git /var/www/task-management
            fi

            cd /var/www/task-management

            # Pull latest code (for nginx config, compose file updates etc.)
            git pull origin main

            # Pull latest Docker image from GHCR
            docker compose pull

            # Restart containers with new image
            docker compose up -d

            # Optional: remove unused images
            docker image prune -f
