name: task-management

on:
  push:
    branches: [ main ]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ghcr.io/nozimjon04/task-management:latest
  PROJECT_DIR: /opt/task-management

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.CICD_TOKEN }}

      - name: Build and Push Image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ env.IMAGE_NAME }}

      - name: Deploy to Server
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            set -e

            # Create project directory if not exists
            if [ ! -d "${PROJECT_DIR}" ]; then
              git clone https://github.com/Nozimjon04/task-management.git ${PROJECT_DIR}
            fi

            cd ${PROJECT_DIR}

            # Always pull latest compose changes
            git pull origin main

            # Login to GHCR
            echo ${{ secrets.CICD_TOKEN }} | docker login ghcr.io -u nozimjon04 --password-stdin

            # Pull new image
            docker compose pull

            # Restart safely
            docker compose up -d --remove-orphans

            # Cleanup old images
            docker image prune -af
